config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'carts/update'
  get 'carts/destroy'
  resources :carts, only: [:show, :update, :destroy]
  post 'add_to_cart/:id', to: 'carts#add_to_cart', as: 'add_to_cart'

  devise_for :users
  resources :orders
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :image
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orderables
  has_many :carts, through: :orderables
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart - Cart.create
      session[:cart_id] = @cart.id
    end
  end

  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = Cart.all
  end

  def add_to_cart
    puts "Params: #{params.inspect}"
    @product = Product.find(params[:id])
    @cart_item = current_cart.cart_items.build(product: @product)
    if @cart_item.save
      redirect_to cart_path, notice: 'Product added to cart successfully.'
    else
      redirect_back fallback_location: root_path, alert: 'Failed to add product to cart.'
    end
  end

  def update
    @cart_item = Cart.find(params[:id])
    if @cart_item.update(cart_params)
      redirect_to cart_path, notice: "Cart updated successfully."
    else
      render :show
    end
  end

  def destroy
    @cart_item = Cart.find(params[:id])
    @cart_item.destroy
    redirect_to cart_path, notice: "Product removed from cart."
  end

  private

  def cart_params
    params.require(:cart).permit(:quantity)
  end

  def current_cart
    if session[:cart_id].present?
      cart = Cart.find_by(id: session[:cart_id])
      puts "Existing Cart ID: #{cart.id if cart}"
      cart || Cart.new
    else
      cart = Cart.create
      session[:cart_id] = cart.id
      puts "New Cart ID: #{cart.id}"
      cart
    end

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_name, :total_price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]


  # GET /products or /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 6)
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<h1>Your Shopping Cart</h1>
<% if @cart.nil? %>
        <h1>Your cart is empty.</h1>
    <% else %>
        <% @cart.each do |item| %>
            <%= render "/shared/cart_item" %>
        <% end%>
<% end %>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
 
  </head>

  <body>
    <%= render "/shared/header"%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_name, style: "display: block" %>
    <%= form.text_field :customer_name %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Customer name:</strong>
    <%= order.customer_name %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <%= form.hidden_field :id, value: product.id %>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div class="card" style="width: 18rem;">
    <%= image_tag product.image if product.image.attached? %>
    <div class="card-body">
      <h3><strong><%= product.name %></strong></h3>
      <p class="card-text"><%= product.description %></p>
      <p><%= number_to_currency product.price %></p>
      <p><%= link_to "Show this product", product, class: "btn btn-primary" %></p>
     
          <%= form_tag add_to_cart_path(product.id), method: :post do %>
            <%= submit_tag "Add to Cart" %>
          <% end %>

    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Products</h1>
  <br>
    <div class="row">
    <% @products.each do |product| %>
    <div class="col-md-3">
      <%= render product %>
      
    </div>
    <% end %>
  </div>

</div>
  <div class="container d-flex justify-content-center py-5">
    <%= will_paginate @products, class: "amazoon_pagination" %>
  </div>


 
  
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_cart_item.html.erb
<div class="cart-item">
  <p><%= cart_item.product.name %></p>
  <p>Quantity: <%= cart_item.quantity %></p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Amazoon", root_path, class: "navbar-brand text-warning" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign-In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <%end%>
        
        
        <% if user_signed_in? %>
          <%= link_to "New product", new_product_path, class: "nav-link text-success "%>
          <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-danger" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>